### ISSUE TITLE
The v0.5.0 release does not include assets resulting in failed installs

### ISSUE THREAD

**Issue by jwalgran** [ethanmdavidson/packer-plugin-git#107]
The v0.5.0 release published December 15 2023 does not include assets. Trying to install this version fails because the assets cannot be downloaded.

<img width="638" alt="Screenshot 2023-12-19 at 4 05 24 PM" src="https://github.com/ethanmdavidson/packer-plugin-git/assets/17363/78fca2d1-7dd8-4db3-a736-b5abb0ef46aa">

The previous releases include assets

<img width="643" alt="Screenshot 2023-12-19 at 4 10 04 PM" src="https://github.com/ethanmdavidson/packer-plugin-git/assets/17363/cfab7b97-7715-4ac5-8b1e-1e9361dca17b">

**Comment by ethanmdavidson** [comment]
Hi @jwalgran! thanks for opening a ticket. This is a known issue - I think I broke something, but I'm not exactly sure what. See [this comment](https://github.com/ethanmdavidson/packer-plugin-git/pull/100#issuecomment-1861906380) for more info.

For now, please just pin to v0.4 of the plugin.

**Comment by jwalgran** [comment]
Pinning to a pre v0.5.0 release is a successful workaround. Thank you.

**Comment by ethanmdavidson** [comment]
I've deleted the v0.5.0 release, to hopefully reduce the chance of any further confusion. I'm still working on fixing the release process.

**Comment by ethanmdavidson** [comment]
A [new v0.5.0 release](https://github.com/ethanmdavidson/packer-plugin-git/releases/tag/v0.5.0) has been created, and it appears to have all the necessary assets. Please try it out and lmk if it works or not.

cc @andremarianiello

**Comment by jwalgran** [comment]
The [new v0.5.0 release](https://github.com/ethanmdavidson/packer-plugin-git/releases/tag/v0.5.0) is working in my build. Thank you.
