### ISSUE TITLE
New datasource HEAD

### ISSUE THREAD

**Issue by daroga0002** [ethanmdavidson/packer-plugin-git#14]
I think very beneficial in CI/CD pipelines will be having new data source `git-head`. It will be similar to `git-commit` but not focusing over commit, but rather on current git repo workspace. 

Data source as input will be taking path (by default `.`) and always working on HEAD commit. As output it will initially return two values:
- git commit sha
- current git branch name

Alternatives:
we can add one output into git-commit with branch name associated with HEAD but by design of git-commit it doesnt seems to be fitting there (there is focus over commit object)

@ethanmdavidson  what you think here?

**Comment by ethanmdavidson** [comment]
I've been thinking about how to structure this, and I've settled on adding a datasource named `repository`, with an output `head` which contains the current value of head. Please look over pr #15 and let me know if you think that will fulfill your needs.
