### ISSUE TITLE
Doc Issue: README has old name/location

### ISSUE THREAD

**Issue by matthewsht** [ethanmdavidson/packer-plugin-git#79]
packer {
  required_plugins {
    git = {
      version = ">= 0.3.5"
      source  = "github.com/ethanmdavidson/git"
    }
  }
}

Which I think now is github.com/ethanmdavidson/packer-plugin-git

**Comment by ethanmdavidson** [comment]
No, the name has not been changed. This is just how packer matches the plugin source to the repo name.

> For example, the fictional `myawesomecloud` plugin could belong to the `hashicorp` namespace on `github.com`, so its `source` could be `github.com/hashicorp/myawesomecloud`,

> Note: the actual repository that myawesomecloud comes from must always have the name format `github.com/hashicorp/packer-plugin-myawesomecloud`, but the `required_plugins` block omits the redundant `packer-plugin-` repository prefix for brevity.

https://developer.hashicorp.com/packer/docs/plugins/install-plugins#source-addresses

**Comment by matthewsht** [comment]
AH - my mistake. Thank You for the clarification.
