### ISSUE TITLE
query: is it possible for this plugin to say whether the working dir is "clean" or not?

### ISSUE THREAD

**Issue by matthewsht** [ethanmdavidson/packer-plugin-git#80]
Using this plugin with the syntax:
data "git-commit" "cwd-head" { }

//  BLOCK: locals
//  Defines the local variables.

locals {
  truncated_sha = substr(data.git-commit.cwd-head.hash, 0, 8)
  author = data.git-commit.cwd-head.author
}

its possible to get the hash of the last checkin.

But if any changes have been made in the working directory, that won't be reflected in the truncated_hash.
Is it possible to get a binary/boolean on wether the working directory was "clean" when it was run?

**Comment by ethanmdavidson** [comment]
Yep, that is possible. The [repository object has an `is_clean` output](https://developer.hashicorp.com/packer/plugins/datasources/git/repository?ajs_aid=6e84f091-f191-4d03-b8ac-cb0d14d773fa&product_intent=packer#output), so you should be able to do something like:

```hcl
data "git-repository" "cwd-head" { }

locals {
  is_clean = data.git-repository.cwd-head.is_clean
}
```

Check out [this example that uses is_clean](https://github.com/ethanmdavidson/packer-plugin-git/blob/main/example/repository.pkr.hcl).

**Comment by matthewsht** [comment]
COuld this and other examples be added to the README?
(and yes, this was exactly the flag I was looking for ...)

**Comment by ethanmdavidson** [comment]
That's a good idea! I've updated the README to link to the examples directory. I don't want to put examples in the README itself because then I would have two places that need to be updated when things change.
