### ISSUE TITLE
Feature (or doc) : how to tell which branch is currently checked out.

### ISSUE THREAD

**Issue by matthewsht** [ethanmdavidson/packer-plugin-git#98]
I'm trying to include logic in my packer build so that if the repo isn't clean and the currently checked out branch isn't "main" then a prod build is impossible.

I have the code for "isclean" -- thank you.
Is there any code for the checked out branch? I've seen "branches" -- which is an array.

Sorry -I'm not a git expert and am not sure why a commit would have an array for branches.

**Comment by ethanmdavidson** [comment]
Hi! You should be able to do that with the `repository` datasource. Something like this:

```hcl
data "git-repository" "cwd" {}

locals {
  onMain = data.git-repository.cwd.head == "main"
}
```

`onMain` will be a boolean, true if the current branch is named `main`.

This is shown [in the docs here](https://github.com/ethanmdavidson/packer-plugin-git/blob/main/docs/datasources/repository.mdx#L50)
